### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by giorgigona** [d-ailin/GDN#28]
I tried to run the code on Ubuntu 16.04 machine without GPU.

I run CPU version of code, but it does not work.

~/gitlab/GDN-main$ bash run.sh cpu msl
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from models.GDN import GDN
  File "/home/giorgi/gitlab/GDN-main/models/GDN.py", line 12, in <module>
    from .graph_layer import GraphLayer
  File "/home/giorgi/gitlab/GDN-main/models/graph_layer.py", line 4, in <module>
    from torch_geometric.nn.conv import MessagePassing
  File "/home/giorgi/gitlab/GDN-main/gnn_venv/lib/python3.6/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/giorgi/gitlab/GDN-main/gnn_venv/lib/python3.6/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/giorgi/gitlab/GDN-main/gnn_venv/lib/python3.6/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/giorgi/gitlab/GDN-main/gnn_venv/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/giorgi/gitlab/GDN-main/gnn_venv/lib/python3.6/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/giorgi/gitlab/GDN-main/gnn_venv/lib/python3.6/site-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/giorgi/gitlab/GDN-main/gnn_venv/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/opt/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.10: cannot open shared object file: No such file or directory

**Comment by d-ailin** [comment]
Hi, I guess this issue can be solved by installing the CPU version of torch_geometric related packages.

Maybe you could try with:
```
pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.5.0+cpu.html
pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.5.0+cpu.html
pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-1.5.0+cpu.html
pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.5.0+cpu.html
```

More details can be refer to https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html.

**Comment by giorgigona** [comment]
Thanks it worked!
