### ISSUE TITLE
Error occurs when starting training

### ISSUE THREAD

**Issue by zhujun001** [d-ailin/GDN#6]
Hi,
I encounter such error when just running command "bash run.sh 0 msl". Any idea about it? Thanks!

Traceback (most recent call last):
  File "main.py", line 256, in <module>
    main.run()
  File "main.py", line 108, in run
    self.train_log = train(self.model, model_save_path, 
  File "/media/home/jzhu/projects/GDN-main/train.py", line 70, in train
    out = model(x, edge_index).float().to(device)
  File "/media/home/jzhu/anaconda3/envs/py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/home/jzhu/projects/GDN-main/models/GDN.py", line 167, in forward
    gcn_out = self.gnn_layers[i](x, batch_gated_edge_index, node_num=node_num*batch_num, embedding=all_embeddings)
  File "/media/home/jzhu/anaconda3/envs/py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/home/jzhu/projects/GDN-main/models/GDN.py", line 73, in forward
    out, (new_edge_index, att_weight) = self.gnn(x, edge_index, embedding, return_attention_weights=True)
  File "/media/home/jzhu/anaconda3/envs/py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/home/jzhu/projects/GDN-main/models/graph_layer.py", line 72, in forward
    out = self.propagate(edge_index, x=x, embedding=embedding, edges=edge_index,
  File "/media/home/jzhu/anaconda3/envs/py3/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 253, in propagate
    out = self.aggregate(out, **aggr_kwargs)
  File "/media/home/jzhu/anaconda3/envs/py3/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 287, in aggregate
    return scatter(inputs, index, dim=self.node_dim, dim_size=dim_size,
  File "/media/home/jzhu/anaconda3/envs/py3/lib/python3.8/site-packages/torch_scatter/scatter.py", line 153, in scatter
    return scatter_sum(src, index, dim, out, dim_size)
  File "/media/home/jzhu/anaconda3/envs/py3/lib/python3.8/site-packages/torch_scatter/scatter.py", line 11, in scatter_sum
    index = broadcast(index, src, dim)
  File "/media/home/jzhu/anaconda3/envs/py3/lib/python3.8/site-packages/torch_scatter/utils.py", line 13, in broadcast
    src = src.expand_as(other)
RuntimeError: The expanded size of the tensor (1) must match the existing size (4320) at non-singleton dimension 1.  Target sizes: [4320, 1, 64].  Tensor sizes: [1, 4320, 1]

**Comment by QianFanCe** [comment]
I meet the problem too, try this:
pip install torch-geometric==1.5.0

**Comment by lovechang1986** [comment]
I meet the same issue.
Would you like to update the GDN based on the latest version of torch_geometric?

**Comment by fede-bello** [comment]
Could anyone fix this problem with a more recent version of `pytorch_geometric`? 1.5 is quite deprecated nowadays

**Comment by dsorens01** [comment]
Ok I think I solved the issue, or at least patched it for a while. So the problem is that the default dimension along which to index is -2 while the one we want to index over is 0. So in the init method of MessagePassing (found in torch_geometric/nn/conv/message_passing.py) I changed the default value of node_dim to 0. No idea what other consequences this has, so I would recommend to create a dedicated environment for this alteration of pytorch-geometric, at least while another solution does not appear.

**Comment by xuridongshengpxd** [comment]
> Ok I think I solved the issue, or at least patched it for a while. So the problem is that the default dimension along which to index is -2 while the one we want to index over is 0. So in the init method of MessagePassing (found in torch_geometric/nn/conv/message_passing.py) I changed the default value of node_dim to 0. No idea what other consequences this has, so I would recommend to create a dedicated environment for this alteration of pytorch-geometric, at least while another solution does not appear.

Maybe you don't need to modify torch_geometric/nn/conv/message_passing.py. You just need to adjust the configuration parameters when inheriting the parent class. The specific code is as follows:
from torch_geometric.nn import MessagePassing

class GraphLayer(MessagePassing):
    def __init__(self, ...):
     
        super().__init__(aggr='add', node_dim=0)  # Add node_dim=0
