### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by Andred00** [d-ailin/GDN#74]
I'm trying to use your implementation for a project, while running the train function I get this error: RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x55 and 15x64).

55 is the number of features of my dataset
15 sliding window 
64 dim

**Comment by d-ailin** [comment]
Thanks for your interest. Could you provide more details, such as the error stack trace and the config?

**Comment by Andred00** [comment]
Traceback (most recent call last):
  File "/Users/andrea/Desktop/Andrea/PoliTo/Machine Learning in Applications/project/mla-prj-23-fp-01-g02/code/GDN/main.py", line 127, in <module>
    main.run()
  File "/Users/andrea/Desktop/Andrea/PoliTo/Machine Learning in Applications/project/mla-prj-23-fp-01-g02/code/GDN/main.py", line 67, in run
    self.train_log = train(self.model, model_save_path, 
  File "/Users/andrea/Desktop/Andrea/PoliTo/Machine Learning in Applications/project/mla-prj-23-fp-01-g02/code/GDN/train.py", line 71, in train
    out = model(x, edge_index).float().to(device)
  File "/Users/andrea/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/andrea/Desktop/Andrea/PoliTo/Machine Learning in Applications/project/mla-prj-23-fp-01-g02/code/GDN/models/GDN.py", line 163, in forward
    gcn_out = self.gnn_layers[i](x, batch_gated_edge_index, node_num=node_num*batch_num, embedding=all_embeddings)
  File "/Users/andrea/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../code/GDN/models/GDN.py", line 70, in forward
    out, (new_edge_index, att_weight) = self.gnn(x, edge_index, embedding, return_attention_weights=True)
  File ".../anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../code/GDN/models/graph_layer.py", line 56, in forward
    x = self.lin(x)
  File ".../anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../anaconda3/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x55 and 15x64)


My train config is train_config = {
        'batch': 128,
        'epoch': 1,
        'slide_win': 15,
        'dim': 64,
        'slide_stride': 5,
        'seed': 42,
        'out_layer_num': 1,
        'out_layer_inter_dim': 256,
        'decay': 0,
        'val_ratio': 0.1,
        'topk': 20
    }

**Comment by Andred00** [comment]
Traceback (most recent call last):
File ".../code/GDN/main.py", line 127, in 
main.run()
File ".../code/GDN/main.py", line 67, in run
self.train_log = train(self.model, model_save_path,
File ".../code/GDN/train.py", line 71, in train
out = model(x, edge_index).float().to(device)
File ".../anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(input, **kwargs)
File ".../code/GDN/models/GDN.py", line 163, in forward
gcn_out = self.gnn_layers[i](x, batch_gated_edge_index, node_num=node_numbatch_num, embedding=all_embeddings)
File ".../anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File ".../code/GDN/models/GDN.py", line 70, in forward
out, (new_edge_index, att_weight) = self.gnn(x, edge_index, embedding, return_attention_weights=True)
File ".../anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File ".../code/GDN/models/graph_layer.py", line 56, in forward
x = self.lin(x)
File ".../anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
return forward_call(*input, **kwargs)
File ".../anaconda3/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x55 and 15x64)

My train config is train_config = {
'batch': 128,
'epoch': 1,
'slide_win': 15,
'dim': 64,
'slide_stride': 5,
'seed': 42,
'out_layer_num': 1,
'out_layer_inter_dim': 256,
'decay': 0,
'val_ratio': 0.1,
'topk': 20
}

**Comment by d-ailin** [comment]
I guess it is caused by the incorrect input data format. Here, the input's shape should be in something like (batch_size, slide_win).

**Comment by Andred00** [comment]
The input's shape is actually torch.Size([batch_size, n_nodes, slide_win]).
Is it correct? I get very high loss value, so I think I'm making some mistakes..
